# Generated by Django 4.2 on 2023-04-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brand',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
