# Generated by Django 4.2 on 2023-04-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='brand',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shirt',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shirt',
            name='is_bestSeller',
            field=models.BooleanField(default=False),
        ),
    ]
