# Generated by Django 4.2 on 2023-04-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_shirt_brand_shirt_description_shirt_is_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('brand', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
